---
- name: Upload new code and ReStart the service
  hosts: 192.168.6.64
  vars:
    - app: apache2

  tasks:
  -  name: Place custom HTML File
     copy:
       src: /var/lib/jenkins/workspace/website-update/index.html
       dest: /var/www/html/index.html
     become: true

  - name: Start the service
    service:
      name: apache2
      state: restarted
      enabled: yes
    become: true
